import { Metadata } from 'next';
import Link from 'next/link'
import React from 'react'
export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by Mohamad Osman Goni",
};
 
export default function page() {
  const blogs=[{
    id:"1",
    title:"Blog 1",
    description:"Blog number 1 description"
},
{
    id:"2",
    title:"Blog 2",
    description:"Blog number 2 description"
},
{
    id:"3",
    title:"Blog 3",
    description:"Blog number 3 description"
},
]
  return (
    <div>
      {
        blogs.map((blog)=>{
            return(
                <li key={blog.id}><Link href={`/blog/${blog.id}`}>{blog.title}</Link></li>
            )
        })
      }
    </div>
  )
}