import { Metadata } from "next";

interface PageProps {}
export const metadata: Metadata = {
  title: "Practice Next App",
  description: "Generated by Mohamad Osman Goni",
};
const Page = ({}: PageProps) => {

  return (
    <div>
      <h1>About Page</h1>
     
    </div>
  );
};

export default Page;
