import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Practice Next App",
  description: "Generated by Mohamad Osman Goni",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="m-5">
      <body className={inter.className}>
        <nav>
          <ul className="flex gap-5 text-md items-center p-2 mb-4">
            <li><Link href={"/"}>Home</Link></li>
            <li><Link href={"/about"}>About</Link></li>
            <li><Link href={"/blog"}>Blog</Link></li>
            <li><Link href={"/user"}>User</Link></li>
            
          </ul>
        </nav>
        <hr/>
        {children}</body>
    </html>
  );
}
